/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/book.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Book(props) {
  const { nodes, materials } = useGLTF('../models/book.gltf');
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.012, 0.137, 0.058]}
        rotation={[0, -1.452, 0]}
        scale={[0.275, 0.062, 0.365]}>
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.list} />
      </group>
      <group
        position={[-0.012, 0.01, 0.058]}
        rotation={[Math.PI, -1.387, Math.PI]}
        scale={[0.275, 0.062, 0.365]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.list} />
      </group>
      <group
        position={[-0.012, -0.113, 0.058]}
        rotation={[Math.PI, -1.445, Math.PI]}
        scale={[0.275, 0.062, 0.365]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.book} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials.list} />
      </group>
    </group>
  );
}

useGLTF.preload('../models/book.gltf');
