/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/chair.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Chair(props) {
  const { nodes, materials } = useGLTF('../models/chair.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.364, 0]} scale={[0.043, 0.05, 0.043]}>
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  );
}

useGLTF.preload('../models/chair.gltf');
