/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cube.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Cube(props) {
  const { nodes, materials } = useGLTF('../models/cube.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.322, 0]} rotation={[Math.PI, -1.211, Math.PI]} scale={9.405}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Cube002_4.geometry} material={materials['Material.053']} />
        <mesh geometry={nodes.Cube002_5.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Cube002_6.geometry} material={materials['Material.066']} />
      </group>
    </group>
  );
}

useGLTF.preload('../models/cube.gltf');
