/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/cup.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Cup(props) {
  const { nodes, materials } = useGLTF('../models/cup.gltf');
  return (
    <group {...props} dispose={null} scale={0.7}>
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials['Material.014']}
        position={[0, 0.335, 0]}
        rotation={[-Math.PI, 1.183, -Math.PI]}
        scale={2.33}
      />
    </group>
  );
}

useGLTF.preload('../models/cup.gltf');
