/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/pictures.gltf 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Pictures(props) {
  const { nodes, materials } = useGLTF('../models/pictures.gltf');
  return (
    <group {...props} dispose={null}>
      <group position={[-0.157, -0.014, 0.35]} rotation={[Math.PI / 2, 0, -1.126]} scale={1.264}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['Material.007']} />
      </group>
      <group position={[-0.147, 0.764, 0.354]} rotation={[Math.PI / 2, 0, -1.126]} scale={1.264}>
        <mesh geometry={nodes.Cube026.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.282, 0.378, -0.545]} rotation={[Math.PI / 2, 0, -1.126]} scale={1.264}>
        <mesh geometry={nodes.Cube025.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['Material.007']} />
      </group>
    </group>
  );
}

useGLTF.preload('../models/pictures.gltf');
