/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/pillow.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pillow(props) {
  const { nodes, materials } = useGLTF('../models/pillow.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Grid.geometry} material={materials['Material.013']} scale={0.276} />
    </group>
  )
}

useGLTF.preload('../models/pillow.gltf')
