/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/radio/scene.gltf 
Author: Discover (https://sketchfab.com/Discovered)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-radio-d7d924cb3d1f4b229e2aa62dcee77fd3
Title: Vintage Radio
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Radio(props) {
  const { nodes, materials } = useGLTF('../models/radio/scene.gltf');
  return (
    <group
      {...props}
      dispose={null}
      scale={window.innerWidth > 550 ? 0.01 : 0.006}
      position-y={-0.2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.Details_Mat} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.Case_Mat} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.Case_Mat} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('../models/radio/scene.gltf');
